version: '3'
services:
  application:
    image: krish889/apprepo:appjava
    ports:
      - "1234:8080"
    depends_on:
      - database

  database:
    image: krish889/dbrepo:dbjava
    ports:
      - "3306:3306"
