version: '3'
services:
  vproapp:
    image: krish889/apprepo:myapp
    ports:
      - "8080:8080"
    depends_on:
      - vprodb

  vprodb:
    image: krish889/dbrepo:mydb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass

volumes:
  vprodbdata: {}
